version: "3"
services:
  neo4j:
    container_name: "neo4j"
    image: neo4j:latest
    ports:
      - 7474:7474
      - 6477:6477
      - 7687:7687
    environment:
      - NEO4J_dbms_connector_http_listen__address=:7474
      - NEO4J_dbms_connector_https_listen__address=:6477
      - NEO4J_dbms_connector_bolt_listen__address=:7687
      # - NEO4J_dbms_connector_bolt_listen__address=:7687

  #  volumes:
  #    - ./storage/neo4j:/data